# примеры API-запросов

@baseUrl = http://localhost:8000/api

# получение объявлений
GET {{baseUrl}}/advertisements/
Content-Type: application/json

###

# создание объявления
POST {{baseUrl}}/advertisements/
Content-Type: application/json
Authorization: Token d40a3561e1f74139464eb72cfcfdc32c4bd35283

{
  "title": "Шкаф IKEA",
  "description": "Срочно"
}

###

# удаление объявления
DELETE {{baseUrl}}/advertisements/10/
Content-Type: application/json
Authorization: Token ccbb6a695dbf13fb6ba9fccfdc5138eecf1fe4df

###

# попытка поменять объявление
PATCH {{baseUrl}}/advertisements/13/
Content-Type: application/json
Authorization: Token d40a3561e1f74139464eb72cfcfdc32c4bd35283

{
  "status": "CLOSED"
}

###

# фильтрация по создателю
GET {{baseUrl}}/advertisements/?creator=2
Content-Type: application/json

###

# фильтрация по дате
GET {{baseUrl}}/advertisements/?created_at_after=2023-11-28
Content-Type: application/json

###

# фильтрация по статусу
GET {{baseUrl}}/advertisements/?status=CLOSED
Content-Type: application/json

###

# получение списка избранного
GET {{baseUrl}}/advertisements/favourites/
Content-Type: application/json
Authorization: Token d40a3561e1f74139464eb72cfcfdc32c4bd35283

###

# добавление объявления в избранное
POST {{baseUrl}}/advertisements/17/add_to_favourites/
Content-Type: application/json
Authorization: Token d40a3561e1f74139464eb72cfcfdc32c4bd35283
